spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${GOOGLE_REDIRECT_URI}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
          linkedin:
            redirect-uri: ${LINKEDIN_REDIRECT_URI}

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_NAME}

cors:
  allowed-origins: ${ALLOWED_ORIGINS}